sudo: required
services:
  - docker


before_install:
  - docker build -t aubuchcl/docker-react -f Dockerfile.dev .
  
script:
  - docker run aubuchcl/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-us-west-2-487797487174"
  bucket-path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"